@echo off
echo Building project...
call ng build --configuration production

:: we need to create this 404.html for ghpages to work with angular router
echo Duplicating index.html into 404.html
type "%CD%\docs\index.html" >> "%CD%\docs\404.html"

echo Staging Commits...
call git add --all
set /p msg=Enter Commit Message...
echo Comitting...
call git commit -m "%msg%"
echo Pushing...
call git push