name: Format and Lint

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: 'format-lint-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

env:
  node-version: '20'

on:
  pull_request:
    branches:
      - main
      - 'lint/*'

jobs:
  format-lint-and-open-pr:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run format
        run: npm run format

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - name: Create branch for lint fixes
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          BRANCH="lint/$SHORT_SHA"
          git checkout -b "$BRANCH"
          git add .

          if git diff --cached --quiet; then
            echo "No issues found."
            exit 0
          fi
          git commit -m "chore: auto-format and lint fixes"
          git push -u origin "$BRANCH"

          # Authenticate GitHub CLI
          echo "$GH_TOKEN" | gh auth login --with-token

          PR_NUMBER=$(gh pr create \
            --title "$TITLE" \
            --body "$BODY" \
            --base "${{ github.event.pull_request.head.ref }}" \
            --head "$BRANCH" \
            --label "auto-lint" \
            --json number \
            --jq .number)

          #gh pr merge "$PR_NUMBER" --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: 'Automatic formatting and linting fixes'
          BODY: 'This PR was created automatically by the formatting and linting workflow: `.github/workflows/lint.yml`'
