name: Lint

on:
  pull_request:
    branches:
      - main
      - 'lint-fixes/*'

jobs:
  format-lint-and-open-pr:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .

      - name: Run linter
        run: npm run lint

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix(lint): apply automatic linting and formatting fixes'
          title: 'Automatic linting and formatting fixes'
          body: 'This PR was created automatically by the linting and formatting workflow.'
          branch: 'lint-fixes/${{ github.head_ref }}'

  automerge:
    if: startsWith(github.head_ref, 'lint-fixes/')
    runs-on: ubuntu-latest
    needs: [format-lint-and-open-pr]
    steps:
      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Delete branch after merge
        uses: peter-evans/delete-branch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
