name: Format and Lint

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: 'format-lint-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

env:
  workflow-name: 'format-and-lint'
  node-version: '20'

on:
  pull_request:
    branches:
      - main

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run format
        run: npm run format

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - name: Configure git credentials
        run: |
          git config user.name "${{ env.workflow-name }}"
          git config user.email "workflows@${{ env.workflow-name }}.yml"

      - name: Merge fixes
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          BRANCH="${{ env.workflow-name }}/$SHORT_SHA"
          git checkout -b "$BRANCH"
          git add .

          if git diff --cached --quiet; then
            echo "No issues found."
            exit 0
          fi
          git commit -m "chore: auto-format and lint fixes"
          git push -u origin "$BRANCH"

          gh pr create \
            --title "$TITLE" \
            --body "$BODY" \
            --base "${{ github.event.pull_request.head.ref }}" \
            --head "$BRANCH"

          PR_NUMBER=$(gh pr list \
            --head "$BRANCH" \
            --state open \
            --json number \
            --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "::error ::Failed to detect newly created PR from branch: $BRANCH"
            exit 1
          fi

          gh pr merge "$PR_NUMBER" --merge
        env:
          GH_TOKEN: ${{ github.token }}
          TITLE: 'Automatic formatting and linting fixes'
          BODY: 'This PR was created by the workflow: `.github/workflows/${{ env.workflow-name }}.yml`'
